apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-gateway
  namespace: ruscan
  labels:
    app: spotify-gateway
spec:
  selector:
    matchLabels:
      app: spotify-gateway
  template:
    metadata:
      labels:
        app: spotify-gateway
    spec:
      containers:
        - name: spotify-gateway
          image: ghcr.io/chivta/ruscan/spotify-gateway:placeholder
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          env:
            - name: REDIS_URL
              value: redis://redis:6379
            - name: RABBITMQ_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: RABBITMQ_URL
            - name: SPOTIFY_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPOTIFY_CLIENT_ID
            - name: SPOTIFY_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: SPOTIFY_CLIENT_SECRET
